# Generated by Django 5.0 on 2023-12-29 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoStore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_money_amount',
            field=models.IntegerField(default=10000),
        ),
    ]
