# Generated by Django 5.0 on 2024-01-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoStore', '0002_alter_profile_user_money_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_amount',
            field=models.FloatField(default=0, verbose_name='Кол-во товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.FloatField(default=0, verbose_name='Цена товара'),
        ),
    ]
