# Generated by Django 5.0 on 2024-01-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoStore', '0003_alter_product_product_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseprocess',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
