# Generated by Django 5.0 on 2024-01-09 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoStore', '0005_alter_purchaseprocess_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseprocess',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
