# Generated by Django 5.0 on 2024-01-19 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoStore', '0012_remove_profile_user_money_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='money_amount',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_money_amount',
            field=models.IntegerField(default=10000),
        ),
    ]
