# Generated by Django 5.0 on 2024-01-19 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoStore', '0014_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseprocess',
            name='product_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_processes', to='djangoStore.product'),
        ),
        migrations.AlterField(
            model_name='purchaseprocess',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_processes', to=settings.AUTH_USER_MODEL),
        ),
    ]
